version: "3"

services:
  web:
      container_name: actividad1_unir
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mongo
      volumes:
        - .:/usr/src/app
  mongo:
      container_name: mongodb_database
      image: mongo
      ports:
        - "27018:27017"
      logging:
        driver: none